Hw03 mongodb
PavelLesovoy/nodejs-rest-api pull request #3
Opened 2023-02-15 13:58 UTC by PavelLesovoy

Прошу перевірити домашне завдання

2023-02-15 21:47 UTC, Eastvarga requested changes
Є зауваження

2023-02-15 21:47 UTC, Eastvarga commented on CRUD/contacts/postContact.js
>      }
Саму валідацію треба винести до мідлвару валідації та використовувати перед контроллером (postContact )

2023-02-15 21:47 UTC, Eastvarga commented on CRUD/contacts/updateById.js
теж саме винесіть валідацію у мідлвар

2023-02-15 21:47 UTC, Eastvarga commented on CRUD/contacts/updateStatusContact.js
> +    }
теж саме

2023-02-15 21:47 UTC, Eastvarga commented on routes/api/contacts.js
>  router.post("/", ctrl.postContact);
router.post("/", **addContactValidation**, ctrl.postContact); ось так, приблизно, додайте мідлвар валідації до рауту перед контроллером

2023-02-15 21:47 UTC, Eastvarga commented on routes/api/contacts.js
> +router.put("/:contactId", isValidId, ctrl.updateById);
тут додайте мідлвар валідації оновлення

2023-02-15 21:47 UTC, Eastvarga commented on routes/api/contacts.js
> +router.patch("/:contactId/favorite", isValidId, ctrl.updateStatusContact);
тут мідлвар валідації оновлення поля favorite

2023-02-20 14:50 UTC, PavelLesovoy commented
Прошу перевірити чи правильно я виправив ваші зауваження. 
Також якщо е можливість прощу пояснити чому у файлі routes/api/contact.js після додавання до файлів postContact, updateById, updateStatusContact, довелося змінювати маршрути. через ctrl перестало працювати, и запрацювало лише після вказання конкретного маршруту, ( тобто замість одного const ctrl = require("../../CRUD/contacts"); довелось прописувати три нові 
const { postContact } = require("../../CRUD/contacts/postContact");
const { updateById } = require("../../CRUD/contacts/updateById");
const {updateStatusContact} = require("../../CRUD/contacts/updateStatusContact"); )
Дякую.

2023-02-20 19:08 UTC, Eastvarga commented
Вам потрібно повторити матеріали що до експорту модулів.
Ви з модуля експортуєте
 module.exports = {
  validateAddSchema,
  postContact,
};
А отже те що Ви імпортуєте у index.js це const { postContact, validateAddSchema } = require('./postContact');
але ви чомусь вважаєте що імпортуєте  const postContact = require('./postContact');
отже у змінній postContact  сидить об'єкт { postContact, validateAddSchema } - ось тому Нічого і не виходить.

2023-02-20 19:11 UTC, Eastvarga approved these changes

2023-02-20 19:11 UTC, merged