Hw04 auth
PavelLesovoy/nodejs-rest-api pull request #4
Opened 2023-02-22 15:01 UTC by PavelLesovoy

Прошу перевірити hw04-auth.

2023-02-22 19:01 UTC, Eastvarga requested changes
Є зауваження

2023-02-22 19:01 UTC, Eastvarga commented on CRUD/auth/login.js
> +    }
Валідація повинна бути у окремому мідлварі валідації

2023-02-22 19:01 UTC, Eastvarga commented on CRUD/auth/signup.js
> +    }
Валідація тіла запиту повинна бути у окремому мідлварі валідації котрий стоїть перед контроллером у рауті

2023-02-22 19:01 UTC, Eastvarga commented on CRUD/auth/subscriptionUpdate.js
> +    }
теж саме

2023-02-22 19:01 UTC, Eastvarga commented on CRUD/auth/subscriptionUpdate.js
> +    res.json(result);
Віддавати креди юзера не потрібно (пароль, токен)

2023-02-22 19:01 UTC, Eastvarga commented on middlewares/authenticate.js
> +  if (bearer !== "Bearer") {
токен теж потрібно перевіряти на невизначеність

2023-02-23 12:13 UTC, PavelLesovoy commented
Вітаю! 
Прошу перевірити останні правки стосовно ваших коментарів.
Також хотів би обговорити ситуацію стосовно перших трьох зауважень, стосовно мідлварів. 
У такому вигляді код був написаний спочатку та був перший коміт, після цього я його змінив та виніс валідацию у окремі мідлвари та зробив другий коміт і вже потім пул реквест. Не зрозуміло чому вам видно лише перший коміт, можливо я щось роблю не так, але прошу перевірити чи змінилась ця ситуація з останіми правками що я зробив. 
Дякую.

2023-02-23 18:36 UTC, Eastvarga approved these changes

2023-02-23 18:36 UTC, Eastvarga commented on CRUD/auth/subscriptionUpdate.js
> +    const { creditInfo, ...updateData } = req.body;
А що це таке не зрозуміле?
Вам достатньо підписку витягти з тіла запиту, creditInfo - звідкіля взялось?

2023-02-23 18:36 UTC, merged